### ISSUE TITLE
xref-find-definitions jums to header file

### ISSUE THREAD

**Issue by zaidmsh** [MaskRay/emacs-ccls#16] opened 2018-10-10 06:57 UTC
Hi MaskRay

First of all thank you for the great work you are providing to the community. Second Im having a problem with xref-find-definitions that it is jumping to the '.h' files instead of the '.c' files. I made sure the xref backend functions are lsp-backend-functions and I provided compile_commands.json to the project root directory. To make the command successfully work as it should the '.c' file needs to be opened in a buffer. I don't know why this is happening but I would really like some help. 

Thank you.

Note: I faced this problem with cquery as well

**Comment by MaskRay** [comment] 2018-10-10 16:07
Can you elaborate the files you have?

Is there a declaration in a.h and a corresponding definition in a.c? On a
reference, textDocunent/definition should bring you to the definition if
a.c is indexed

**Comment by zaidmsh** [comment] 2018-10-11 06:37
Thank you for your replay

> Can you elaborate the files you have? Is there a declaration in a.h and a corresponding definition in a.c? 
yes there is and are all in under the same directory src/
> On a reference, textDocument/definition should bring you to the definition if a.c is indexed
how can I make sure it is indexed? I have compile_commands.json in my project root.

Another thing Im not sure if the problem is from ccls or lsp-mode.

**Comment by MaskRay** [comment] 2018-10-11 07:06
Please dump the files.

**Comment by zaidmsh** [comment] 2018-10-11 09:52
executing xref-find-references gives this error message "lsp--location-to-td-position: Wrong type argument: hash-table-p, nil"

**Comment by MaskRay** [comment] 2018-10-11 15:09
The problem is not clearly specified. Please describe a.c a.h compile_commands.json you have. If you suspect your compile_commands.json is illformed you may switch to .ccls

wiki/FAQ describes how to add -log-file= to get more diagnostics.

**Comment by myrgy** [comment] 2018-10-17 12:43
Hello guys,

That's strange, but I got **error: (wrong-type-argument hash-table-p nil)**
That's in my doom-emacs config. While spacemacs works fine.

here it the backtrace from doom-emacs
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("uri" nil)
  lsp--location-to-td-position(nil)
  lsp--symbol-info-to-identifier(#<hash-table equal 6/65 0x3053b4d>)
  mapcar(lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x3053b4d> #<hash-table equal 6/65 0x306f2f1> #<hash-table equal 6/65 0x3098775> #<hash-table equal 6/65 0x30eef85> #<hash-table equal 6/65 0x314ff81> #<hash-table equal 6/65 0x31a976d>))
  #f(compiled-function (function sequence) #<bytecode 0x52e3c1>)(lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x3053b4d> #<hash-table equal 6/65 0x306f2f1> #<hash-table equal 6/65 0x3098775> #<hash-table equal 6/65 0x30eef85> #<hash-table equal 6/65 0x314ff81> #<hash-table equal 6/65 0x31a976d>))
  apply(#f(compiled-function (function sequence) #<bytecode 0x52e3c1>) lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x3053b4d> #<hash-table equal 6/65 0x306f2f1> #<hash-table equal 6/65 0x3098775> #<hash-table equal 6/65 0x30eef85> #<hash-table equal 6/65 0x314ff81> #<hash-table equal 6/65 0x31a976d>) nil)
  seq-map(lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x3053b4d> #<hash-table equal 6/65 0x306f2f1> #<hash-table equal 6/65 0x3098775> #<hash-table equal 6/65 0x30eef85> #<hash-table equal 6/65 0x314ff81> #<hash-table equal 6/65 0x31a976d>))
  #f(compiled-function (backend) #<bytecode 0x155360d>)(xref-lsp)
  apply(#f(compiled-function (backend) #<bytecode 0x155360d>) xref-lsp nil)
  xref-backend-identifier-completion-table(xref-lsp)
  xref--read-identifier("Find references of: ")
  byte-code("\300\301!C\207" [xref--read-identifier "Find references of: "] 2)
  call-interactively(xref-find-references nil nil)
  command-execute(xref-find-references)
```

**Comment by MaskRay** [comment] 2018-10-21 02:33
@zaidmsh Please the close the issue if you believe it is resolved.

@myrgy See `xref-prompt-for-identifier` in https://github.com/MaskRay/ccls/wiki/Emacs#find-definitionsreferences

**Closed by MaskRay** 2018-10-21 02:33 UTC

**Comment by fleutot** [comment] 2022-11-28 09:50
This happens to me regularly, but not always. I think I had the issue before using LSP, though, so it's probably a problem with xref.
